services:
  spark-worker-2:
    <<: *spark-base
    depends_on:
      spark-master:
        condition: service_healthy
    environment:
      <<: *spark-common-env
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: "${WORKER_CORES}"
      SPARK_WORKER_MEMORY: "${WORKER_MEMORY}"
    ports:
      - "${WORKER2_UI_PORT}:8081"
    volumes:
      - ./spark/conf:/opt/bitnami/spark/conf:ro
      - ${HOST_DATA_DIR}:${IN_DOCKER_DATA}
    deploy: *resources-worker
