spark.log.structuredLogging.enabled true
spark.sql.warehouse.dir file:/opt/data/warehouse
spark.hadoop.fs.file.impl org.apache.hadoop.fs.RawLocalFileSystem
spark.eventLog.enabled true
spark.eventLog.dir file:/opt/spark/events
spark.driver.memory 2g
spark.executor.memory 2g
